### ISSUE TITLE
Questions about the dataset you use

### ISSUE THREAD

**Issue by haibo9916** [weisongwen/GraphGNSSLib#10]
Dear author, thank you very much for your open source work. 
I can't understand why you use static data to test GNSS-RTK. Why not use dynamic data testing? 
For GNSS-PPP, the positioning accuracy is poor, and using static data to test the positioning accuracy seems to be a correct choice. 
In addition, I would like to ask, if I want to test the RTK data set I collected, where the code needs to be modified, I only see the need to modify rtklib.h file, I hope you can answer my doubts, thank you!
## Can you test your code just by modifying the coordinates of the reference station?
![image](https://user-images.githubusercontent.com/65943417/158933557-a787c02b-8c75-403c-a49b-03d79224b564.png)

**Comment by haibo9916** [comment]
@weisongwen

**Comment by weisongwen** [comment]
hi @haibo9916 . Thank you for your interest. For your dynamic data, several points you need to modify as below:

1. change the position of the reference station based on your selected station. Usually, the position of the reference station is saved in the obs file of the station receiver. 
2. start and end GPS seconds indicating the time slots that you wish to process
3. the reference point of the ENU coordinates, usually this is selected based on your starting point. 
4. For your dynamic data, you are suggested to change the weighting of the motion model factor associated with the velocity estimated by the Doppler measurements. 
5. one more thing is that, currently, the double-differenced integer ambiguities are not fully connected between epochs which should be connected to increase the feasibility of integer ambiguity resolution. In the coming days, we will have a paper on this advancement. Keep an eye on our update,

**Comment by haibo9916** [comment]
Dear author, thank you for your answer. Where are the start time and end time set? If I set the base station position in the observation file,will it replace the base station position you set in the rtklib.h?

**Comment by haibo9916** [comment]
> hi @haibo9916 . Thank you for your interest. For your dynamic data, several points you need to modify as below:
> 
> 1. change the position of the reference station based on your selected station. Usually, the position of the reference station is saved in the obs file of the station receiver.
> 2. start and end GPS seconds indicating the time slots that you wish to process
> 3. the reference point of the ENU coordinates, usually this is selected based on your starting point.
> 4. For your dynamic data, you are suggested to change the weighting of the motion model factor associated with the velocity estimated by the Doppler measurements.
> 5. one more thing is that, currently, the double-differenced integer ambiguities are not fully connected between epochs which should be connected to increase the feasibility of integer ambiguity resolution. In the coming days, we will have a paper on this advancement with testing on dynamic data in urban cnayons. Keep an eye on our update,

Dear author, thank you for your answer. Where are the start time and end time set? If I set the base station position in the observation file,will it replace the base station position you set in the rtklib.h?

**Comment by haibo9916** [comment]
@weisongwen 
Dear author, thank you for your answer. Where are the start time and end time set? If I set the base station position in the observation file,will it replace the base station position you set in the rtklib.h?

**Comment by weisongwen** [comment]
hi @haibo9916 
start and end gps_sec as below:
![image](https://user-images.githubusercontent.com/24927996/159612162-b774e265-102c-4f56-8958-0a7efe048161.png)

No. You need to manually set the position of the station

**Comment by weisongwen** [comment]
Feel free to reopen if you wish :-)
