### ISSUE TITLE
The question about GraphGNSSLib

### ISSUE THREAD

**Issue by github-hltt3838** [weisongwen/GraphGNSSLib#11]
Dear Welson
 I have a question for you,  when i run the RTK-FGO Demo, as fellow:

source ~/GraphGNSSLib/devel/setup.bash
roslaunch global_fusion dataublox_TST20200603.launch
roslaunch global_fusion psr_doppler_car_rtk.launch

I find that the positioning error is larger than the results mentioned in your paper. 
The maximum positioning error in ENU direction is 3.2 meters。
So, i  want to know why? It is related to the computer? or other reasons?
Thank you very much !

If possible, I would like to add your WeChat. My WeChat account is j15212774116.

**Comment by weisongwen** [comment]
hi @github-hltt3838 . Thank you for your interest.

you evaluate the 3D error or 2D error? In our paper, we only evaluate the 2D error. One more thing is that, currently, the double-differenced integer ambiguities are not fully connected between epochs which should be connected to increase the feasibility of integer ambiguity resolution. In the coming days, we will have a paper on this advancement and we can achieve centimeter-level 3D error on FGO based GNSS-RTK. Keep an eye on our update,

BTW, my WeChat is welsonpolyu

**Comment by github-hltt3838** [comment]
Hi  Welson
I evaluate the  2D error in the east and north direction, and i find that the maximum positioning error in east direction is 3.2 meters.

**Comment by github-hltt3838** [comment]
Dear author, thank you for your answer.   The positioning error in north and east direction  is same as the results mentioned in your paper since i change the weighting of the motion model factor associated with the velocity estimated by the Doppler measurements. However, i find that the positioning  errors in ENU frame are significantly different from that in ECEF frame，and the ground true  track in ECEF  is obtained by llh2ecef() function. Therefore, I have a bold doubt，the ground true track in RTK-FGO Demo is not correct.

**Comment by weisongwen** [comment]
Hi @github-hltt3838 , sorry for the delayed reply :-)

How do you calculate the error in ECEF? The pose in ENU and ECEF essentially points to the same position and different errors from ENU and ECEF should not be related to the accuracy of the ground truth. 

One more thing, the accuracy of the ground truth is within 50 cm.

**Comment by weisongwen** [comment]
Feel free to re-open if necessary :-)
