### ISSUE TITLE
Require: Docker file or image support!

### ISSUE THREAD

**Issue by waynehq** [weisongwen/GraphGNSSLib#12]
Hi,can you provide docker file or image to us?So we can not install the environment ,at the same time run the code as soon as possible.Thank you.

**Comment by weisongwen** [comment]
hi @waynehq , thank you for the interest. Currently, we do not have the docker file. We will make this in our plan and will update you later.

**Comment by weisongwen** [comment]
@Pirkaklo Hi Yihan, do you think we can have the docker file image for the GraphGNSSLib?

**Comment by Pirkaklo** [comment]
Hi Dr.WEN, I think docker does allow users to be more efficient by avoiding some errors from environment configuration. I can add this to the schedule if you wish.

**Comment by Pirkaklo** [comment]
> @Pirkaklo Hi Yihan, do you think we can have the docker file image for the GraphGNSSLib?

Hi Dr.WEN, I think docker does allow users to be more efficient by avoiding some errors from environment configuration. I can add this to the schedule if you wish.

**Comment by weisongwen** [comment]
@Pirkaklo Cool! please update the docker file. Thank you :-)

**Comment by Pirkaklo** [comment]
@waynehq hi, there is a new branch named "test_docker". Could you please try to use this docker file and follow step 5 in README.md to run the GraphGNSSLib?

**Comment by waynehq** [comment]
Thank you for your contribution!!! I Will use the docker to run the code. If any question, respond it.
