### ISSUE TITLE
Code get Stucked when running it

### ISSUE THREAD

**Issue by Akpozi** [weisongwen/GraphGNSSLib#13]
Hello Dr. Weisong,

I had the same issue as seen in https://github.com/weisongwen/GraphGNSSLib/issues/6

![image001](https://user-images.githubusercontent.com/47242233/165239840-503d9fe8-a491-4c2a-b61d-fb67ad9ea380.png)
![image002](https://user-images.githubusercontent.com/47242233/165239860-c687d190-f28a-4a59-8b8a-08ab066a33ee.png)

However, when I ran the code as suggested in https://github.com/weisongwen/GraphGNSSLib/issues/6 :
First run roslaunch global_fusion psr_doppler_fusion.launch first, and then 
run roslaunch global_fusion dataublox_TST20190428.launch shortly after.

It seems to work fine but it still got stucked again as seen in the below image.
![Screenshot from 2022-04-26 09-28-53](https://user-images.githubusercontent.com/47242233/165240552-b99905e2-20ec-4be9-9f78-284dca125547.png)

I first ran this on this terminal: roslaunch global_fusion psr_doppler_fusion.launch
![Screenshot from 2022-04-26 10-05-33](https://user-images.githubusercontent.com/47242233/165241792-2191da91-8d2a-432e-8859-4862ded8076b.png)

then I ran this next: roslaunch global_fusion dataublox_TST20190428.launch
![Screenshot from 2022-04-26 10-06-00](https://user-images.githubusercontent.com/47242233/165241871-0b3154d3-5a5f-4199-b5e5-1c17570f9ed1.png)

Kindly let me know if am missing any step(s).

Should I run these steps on the same terminal? and not on separate terminals

_source ~/GraphGNSSLib/devel/setup.bash
roslaunch global_fusion dataublox_TST20190428.launch
roslaunch global_fusion psr_doppler_fusion.launch_

Thank you for your help.

**Comment by Pirkaklo** [comment]
@Akpozi Hi, thank you for your interest in GraphGNSSLib! For your question, I think all the processes are correct, but the program still seems to get stuck. 

There might be a good way to solve this question quickly:
Recently we have created a docker container to further facilitate the building process [**branch test_docker**].  Could you help us test the docker container?  The steps of using the GraphGNSSLib are shown in README.md under the test_docker branch step 5. 

Also, there is a [video](https://www.youtube.com/watch?v=WMM2de_SxTw) showing the demo after you have built the docker_file in the directory GraphGNSSLib/docker via command
```bash
cd ~/GraphGNSSLib/docker
make build
```

**Comment by Akpozi** [comment]
Hi @Pirkaklo, thank you for your response. The **docker container works well** for the Solution 1 to run the **GNSS positioning Demo**
It generates the "~/GraphGNSSLib/FGO_trajectoryllh_psr_dop_fusion.csv" file. 
Also, can you confirm where the EKF results (output) and WLS output get generated to?

Step taken:
_#define RTK_FGO 0
source ~/GraphGNSSLib/devel/setup.bash
# run pseudorange and doppler fusion
roslaunch global_fusion psr_doppler_fusion.launch
roslaunch global_fusion dataublox_TST20190428.launch_

However, It does not return any output (the "roslaunch global_fusion psr_doppler_car_rtk.launch" get stuck) for the Solution 1 to run the **RTK-FGO Demo**

Steps taken:
_#define RTK_FGO 1
source ~/GraphGNSSLib/devel/setup.bash
# read GNSS raw data and publish as ROS topic
roslaunch global_fusion dataublox_TST20200603.launch
# run GNSS RTK
roslaunch global_fusion psr_doppler_car_rtk.launch_

**Comment by Pirkaklo** [comment]
Hi @Akpozi , for the RTK-FGO Demo, after you change the RTK mode 0->1
```bash
#define RTK_FGO 1
```
please also recompile the program with the command at the **catkin_ws** folder in the container
```bash
catkin_make
```

Unfortunately, for the WLS and EKF results, we do not provide the code at this time.

**Comment by Akpozi** [comment]
Hi @Pirkaklo, thanks for the reply. I have followed the steps mention and I get this error message:
![image](https://user-images.githubusercontent.com/47242233/167349526-f03b59f6-b81f-44da-bd57-9a9fc7fb241f.png)

Did I miss something?

**Comment by Pirkaklo** [comment]
@Akpozi Hi Akpozi, I tried this command on my computer, and it works for me.
For your situation, I think maybe you can try the command as follows:
```bash
rm -rf /build /devel
source devel/setup.bash
catkin_make
```
