### ISSUE TITLE
catkin_make failing on first go

### ISSUE THREAD

**Issue by teku45** [weisongwen/GraphGNSSLib#14]
Hi,

When I am running catkin_make for the first time, it is failing with the following error:

```
WARNING: Catkin package name "nlosExclusion" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, and underscores.
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 3 packages in topological order:
-- ~~  - nlosExclusion
-- ~~  - global_fusion
-- ~~  - rviz_satellite
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'nlosExclusion'
-- ==> add_subdirectory(GraphGNSSLib/nlosExclusion)
-- Could NOT find nodelet (missing: nodelet_DIR)
-- Could not find the required component 'nodelet'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /usr/share/catkin/cmake/catkinConfig.cmake:82 (find_package):
  Could not find a package configuration file provided by "nodelet" with any
  of the following names:

    nodeletConfig.cmake
    nodelet-config.cmake

  Add the installation prefix of "nodelet" to CMAKE_PREFIX_PATH or set
  "nodelet_DIR" to a directory containing one of the above files.  If
  "nodelet" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  GraphGNSSLib/nlosExclusion/CMakeLists.txt:4 (find_package)
```

In my CMakeLists.txt, I get this same error for all of the contents of this

```
find_package(catkin REQUIRED COMPONENTS
  message_filters
  nodelet
  roscpp
  pcl_conversions
  sensor_msgs
  tf2
  tf2_ros
  pcl_ros
  rospy
  std_msgs
  message_generation
)
```

**Comment by Pirkaklo** [comment]
Hi @teku45 , thanks for your interest in GraphGNSSLib!
I think the compilation issues could be quickly solved by the same answer in #12 
Using docker can help you avoid most of the compilation issues if you are the first time to use ROS.

**Comment by weisongwen** [comment]
Hi @teku45 , can you provide the information of your ubuntu system? e.g. version of ubuntu, version of ROS.

**Comment by weisongwen** [comment]
Feel free to re-open this issue if necessary :-)

**Comment by hushengjun2021** [comment]
I had GraphGNSSLib running successfully, but when I was debugging it with VS Code, I encountered the same error”Error from roslaunch:WARNING: Package name "nlosExclusion" does not follow thenaming conventions.  It should start with a lower case letter and onlycontain lower case letters, digits, underscores, and dashes“. My launch file is as follows:{

    "version": "0.2.0",
    "configurations": [
        {
            "name": "ROS: Launch",
            "request": "launch",
            "target": "/home/xxx/GraphGNSSLib/src/GraphGNSSLib/global_fusion/launch/gnss_preprocessor/xxx_data_process.launch",
            "launch": [
                "rviz",
                "gz",
                "gzclient",
                "gzserver"
            ],
            "type": "ros"
        },
        {
            "name": "ROS: Launch",
            "request": "launch",
            "target": "/home/xxx/GraphGNSSLib/src/GraphGNSSLib/global_fusion/launch/gnss_estimator/psr_doppler_fusion.launch",
            "launch": [
                "rviz",
                "gz",
                "gzclient",
                "gzserver"
            ],
            "type": "ros"
        }
    ]
}

**Comment by Pirkaklo** [comment]
@hushengjun2021 If you use vs code to debug the ros program, you need to revise all the **nlosExclusion** to **nlosexclusion**, all uppercase letters should be made lowercase,  also revise the name of the folder.
