### ISSUE TITLE
GPS locations are displayed on Google Maps in real time

### ISSUE THREAD

**Issue by waynehq** [weisongwen/GraphGNSSLib#15]
I need your help! 
I want to use google map to display GPS location  in real time. How?
Thank you for your guidance

**Comment by weisongwen** [comment]
hi @waynehq , we did not have a good solution to load google Maps in real-time. As I know, the API of google map is closed sourced.

**Comment by weisongwen** [comment]
Feel free to re-open if necessary :-)
