### ISSUE TITLE
question about graphgnsslib

### ISSUE THREAD

**Issue by krunt** [weisongwen/GraphGNSSLib#16]
Hi, thanks for your work!
Could you tell pls what's the logic under checkCarrierPhaseConsistency?

Any ideas how to extend your solution to work with other satellite types
like glonass, etc. (all satellites which rtklib currently supports?)
for rtk (psr_doppler_car_rtk)?

**Comment by krunt** [comment]
Another question: why when you successfully fixed last epoch state 
you do not assign it to state_array to use in subsequent epochs?

**Comment by weisongwen** [comment]
> 

This is done by simply check the availability of carrier-phase. Sometimes we find that the carrier-phase from the obs file is a very small values.

**Comment by weisongwen** [comment]
> Hi, thanks for your work! Could you tell pls what's the logic under checkCarrierPhaseConsistency?
> 
> Any ideas how to extend your solution to work with other satellite types like glonass, etc. (all satellites which rtklib currently supports?) for rtk (psr_doppler_car_rtk)?


This is done by simply checking the availability of carrier phase. Sometimes we find that the carrier phase from the obs file is a very small value.

**Comment by weisongwen** [comment]
> Another question: why when you successfully fixed last epoch state you do not assign it to state_array to use in subsequent epochs?

Good question :-). In fact, we only provide epoch-by-epoch integer ambiguity resolution. You can definitely apply the fixed and hold mode of integer ambiguity resolution by doing as you mentioned.

**Comment by krunt** [comment]
Thanks!

**Comment by weisongwen** [comment]
Feel free to re-open if necessary :-)
