### ISSUE TITLE
A code logic problem

### ISSUE THREAD

**Issue by michaelnbk** [weisongwen/GraphGNSSLib#19]
Wen博士， 对于psr_doppler_car_rtk_dyna.h中的addDopplerFactors函数, 每个历元都掉用了 dopplerConstraint::create 工厂函数，在这个函数里一直在重复参数块的清除和循环重新绑定，直接添加最新的状态不可以吗，有什么特殊的逻辑？感谢回答

**Comment by weisongwen** [comment]
Hi @michaelnbk , thank you for your feedback. There is no special logic purpose here. This can be easily be modified to the incremental mode. :-0
