### ISSUE TITLE
[Bug]  the results of NAN in the WeightedLeastSquare function

### ISSUE THREAD

**Issue by timuxi** [weisongwen/GraphGNSSLib#22]
Hi, Professor  @weisongwen  there is a bug in the WeightedLeastSquare function in the gnss_tools.h file.
That is, you use 0 and 1 to represent whether the satellite is Beidou or GPS in the third and fourth columns of the **eH_Matrix** 

 However, if all satellites are Beidou or GPS in this case, then during this step of calculation 
`eDeltaPos = (eH_Matrix.transpose() * weight_matrix * eH_Matrix).inverse() * eH_Matrix.transpose() * weight_matrix * eDeltaPr;`

 eH_Matrix.transpose() * weight_matrix * eH_Matrix is a singular matrix and cannot be inverted, resulting in a nan result finally.

**Comment by Pirkaklo** [comment]
@timuxi Thanks for your comments.  You are right, if only GPS or Beidou is observed, the algorithm will not work. We did not consider the situation that only GPS or Beidou measurements at the single epoch. You can revise it for your cases ^_^
