### ISSUE TITLE
运行roslaunch global_fusion psr_doppler_car_rtk.launch没有结果.csv文件的输出？

### ISSUE THREAD

**Issue by butterflying10** [weisongwen/GraphGNSSLib#23]
您好，我注意到在psr_doppler_car_rtk.launch中并未有logPath的设置，而在psr_doppler_fusion.launch中有logPath的设置，这是不是就意味着FGO-RTK时是不会输出.csv的结果文件呢？感谢！

**Comment by Yoolights** [comment]
> 您好，我注意到在psr_doppler_car_rtk.launch中并未有logPath的设置，而在psr_doppler_fusion.launch中有logPath的设置，这是不是就意味着FGO-RTK时是不会输出.csv的结果文件呢？感谢！

程序上来看是的，仿照psr_doppler_fusion.cpp中结果输出方式更改代码即可，同时在launch文件中设置你需要的logPath
