### ISSUE TITLE
Any plan to integrate more sensors, such as LiDAR and vision?

### ISSUE THREAD

**Issue by eastnav2015** [weisongwen/GraphGNSSLib#5]
Since the remaining error can still reach more than 7 meters, do you have any plan to integrate more sensors, such as LiDAR and Vision? In structured environments, the LiDAR and Vision usually works well.

**Comment by weisongwen** [comment]
Thank you for your interest! Yes! 

- **Vision and GNSS**: We are investigating the complementary integration of the vision and GNSS in our recent work which is currently under submission, and we will share the manuscript once it is accepted. 
- **LiDAR and GNSS**: We continuously developed the 3D LiDAR aided GNSS positioning in urban canyons in the past years. Our latest work in [Wen, Weisong, and Li-Ta Hsu. "3D LiDAR Aided GNSS Real-time Kinematic Positioning." In Proceedings of the 34th International Technical Meeting of the Satellite Division of The Institute of Navigation (ION GNSS+ 2021), pp. 2212-2220. 2021.](https://www.ion.org/publications/abstract.cfm?articleID=18072) proposed a 3D LiDAR aided GNSS real-time kinematic positioning method. 

Best,
Weisong,

**Comment by eastnav2015** [comment]
> Thank you for your interest! Yes!
> 
> * **Vision and GNSS**: We are investigating the complementary integration of the vision and GNSS in our recent work which is currently under submission, and we will share the manuscript once it is accepted.
> * **LiDAR and GNSS**: We continuously developed the 3D LiDAR aided GNSS positioning in urban canyons in the past years. Our latest work in [Wen, Weisong, and Li-Ta Hsu. "3D LiDAR Aided GNSS Real-time Kinematic Positioning." In Proceedings of the 34th International Technical Meeting of the Satellite Division of The Institute of Navigation (ION GNSS+ 2021), pp. 2212-2220. 2021.](https://www.ion.org/publications/abstract.cfm?articleID=18072) proposed a 3D LiDAR aided GNSS real-time kinematic positioning method.
> 
> Best, Weisong,

Those topics sounds to be interesting. I believe that both the LiDAR and camera can be helpful to GNSS in urban canyons.
