### ISSUE TITLE
Something about the Stuck problem

### ISSUE THREAD

**Issue by vincenth2018** [weisongwen/GraphGNSSLib#6]
Dear Dr Wen：
Thank you for sharing the repository, I'm trying to run the code, but It is stuck in the "---> psr_doppler_car_rtk_node Started", and nothing happended next. 
The raw data read and publish launch "dataublox_TST20190428.launch" is running perfectly. After launching this, I typed Ctrl+C to stop, and then roslaunch the "psr_doppler_fusion.launch" but it is stuck, I don't konw whether I missed something important?  Can you help me with this peoblem?

**Comment by vincenth2018** [comment]
Thank you for your reply, I've set the variable `#define RTK_FGO 1` when launching the "psr_doppler_car_rtk.launch"

and `#define RTK_FGO 0` when launching the "psr_doppler_fusion.launch".

I've been trying **"Ctrl+C"** several times. However, it is still stuck.

**Comment by weisongwen** [comment]
Hi, please show me more details about the stuck. For example, a snapshot of the issue.

**Comment by vincenth2018** [comment]
The “dataublox_TST20200603.launch” ran perfectly as the first picture shows.
![image](https://user-images.githubusercontent.com/94587707/142626747-79a6b97e-da30-4290-b78c-19b357e7a0b3.png)
After launching the "psr_doppler_car_rtk.launch", It was stuck in the "---> psr_doppler_car_rtk_node Started" as the second picture shows.
![image](https://user-images.githubusercontent.com/94587707/142627184-d28a16b7-8aa2-4290-be66-99f4dfc4cf48.png)
Should there be more info to publish after the "---> psr_doppler_car_rtk_node Started"?

**Comment by weisongwen** [comment]
Yes! Some results should be printed. It seems that the rostopic is not successfully subscribed by the **psr_doppler_car_rtk_node**. I try the repository on my computer again and it works pretty fine. Can you just clean the GraphGNSSLib package in your computer and clone it and make it again?

**Comment by vincenth2018** [comment]
Hi, I cleaned the GraphGNSSLib package and re-cloned it and re-made it several times, But it is still the same.

**Comment by vincenth2018** [comment]
Hi Dr. Wen, It worked fine finally.  For the first run, I need to run `roslaunch global_fusion psr_doppler_fusion.launch` **first**, and then run `roslaunch global_fusion dataublox_TST20190428.launch` **shortly after**. Then they will both work out fine.

**Comment by weisongwen** [comment]
Hi @vincenth2018 , good to hear that the problem is solved.
