### ISSUE TITLE
missing GNSS_Raw_Array.h file

### ISSUE THREAD

**Issue by xiaoguorui** [weisongwen/GraphGNSSLib#7]
Hi, thanks for the nice work. In gnss_tools.h, there is a missing include file at "#include <nlosExclusion/GNSS_Raw_Array.h>".  I didn't find the file in that location and other locations. Would you please tell me how to access the file?

**Comment by weisongwen** [comment]
Hi @xiaoguorui , thank you for your interest. The head file 
`#include <nlosExclusion/GNSS_Raw_Array.h>`
is from https://github.com/weisongwen/GraphGNSSLib/tree/main/nlosExclusion. Have you cloned the whole package from GraphGNSSLib?

BTW, please also try the following and make again,
`
source devel/setup.bash
`

**Comment by xiaoguorui** [comment]
Thank you for the reply. However, there is no such file in the mentioned directory. Would you please provide a detail link?

**Comment by weisongwen** [comment]
Hi @xiaoguorui , the head file is automatically generated by the estimated ROS msg `https://github.com/weisongwen/GraphGNSSLib/blob/main/nlosExclusion/msg/GNSS_Raw_Array.msg`. In other words, the head file can automatically generate once you finish the catkin_make. BTW, have you try the following and make again?
source devel/setup.bash

You can also provide more information in terms of your issue, e.g. s snapshot can be helpful for me to figure out your problem,

**Comment by xiaoguorui** [comment]
Thank you for the reply. Now I understand what happened. The reason is that I fail to catkin_make, which will not generate the head file. Now, i will try catkin_make on multiple pcs.
