### ISSUE TITLE
The question about GraphGNSSLib

### ISSUE THREAD

**Issue by github-hltt3838** [weisongwen/GraphGNSSLib#9]
When using data collected by ourself, the command " roslaunch global_fusion dataublox_TST20190428.launch " cannot be run.
So why?  what do we need to pay attention to ？

Thank you !

**Comment by weisongwen** [comment]
Thank you for your interest. Have you changed the path of the files in the dataublox_TST20190428.launch? It can be helpful if you can provide more details.

**Comment by weisongwen** [comment]
@github-hltt3838 if this issue is fixed, i will close this. :-0
